### ISSUE TITLE
Module improvements

### ISSUE THREAD

**Issue by pi0** [johannschopplich/nuxt-kql#1]
Hi @johannschopplich! First congratulations on this module. Looks so promising! I've done a quick review and made some options to improve:

- Regarding [handler](https://github.com/johannschopplich/nuxt-kql/blob/main/src/runtime/server/api/kql.ts), you can register it with `method: 'post'` and it automatically registers the router to accept POST method only. Also for throwing errors, you can use `throw createError({ statusCode, statusMesage, body })` it will automatically fill the response.
- For naming auto-generated composables, as is documented it would be much better if they start with `useKql` to avoid name conflicts
- When validating missing options in the module, does it makes sense to add a `return` statement disabling module?
- I find [this](https://github.com/johannschopplich/nuxt-kql/blob/0bb0a962bcb7cd0c65cb529da039f2e9f8e5a171/src/module.ts#L126) little bit complicated. Isn't nitro runtime bundled when we add module path to the _transpile_? Also why you need to force inline it?
- Is [write: true](https://github.com/johannschopplich/nuxt-kql/blob/0bb0a962bcb7cd0c65cb529da039f2e9f8e5a171/src/module.ts#L132) necessary for virtual templates? (Tip: You can debug them using `http://localhost:3000/_vfs`

**Comment by johannschopplich** [comment]
Wow, thank you for the code review, @pi0! Foremost, I want to reiterate how impactful I think your work is. You are not only building the base of Nuxt 3, but taking care of the ecosystem. This feels sustainable. The way you comment on PRs etc. is thoughtful and positive. Such a constructive working ethic. Thank you for the care you put in.

I've already implemented most of the suggestions. Thank you so much! 

One particular issue was noted by your swiftly.

> I find [this](https://github.com/johannschopplich/nuxt-kql/blob/0bb0a962bcb7cd0c65cb529da039f2e9f8e5a171/src/module.ts#L126) little bit complicated. Isn't nitro runtime bundled when we add module path to the _transpile_? Also why you need to force inline it?

Me too. Took me a while to figure out this workaround. Without this Nitro inlining, I get the following error:

```
 ERROR  [worker reload] [worker init] Cannot find module '/Users/johann/Git/nuxt-kql-demo/utils.mjs' imported from /Users/johann/Git/nuxt-kql-demo/.nuxt/dev/index.mjs

  at new NodeError (node:internal/errors:372:5)
  at finalizeResolution (node:internal/modules/esm/resolve:437:11)
  at moduleResolve (node:internal/modules/esm/resolve:1009:10)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)
```

Relative imports to [`utils`](https://github.com/johannschopplich/nuxt-kql/blob/main/src/runtime/utils.ts) doesn't seem to work. For example, I'm importing utils [in a composable](https://github.com/johannschopplich/nuxt-kql/blob/main/src/runtime/composables/%24kql.ts) as well as the [server API route](https://github.com/johannschopplich/nuxt-kql/blob/main/src/runtime/server/api/kql.ts).

Looks like every line

```ts
import { ... } from '../utils'
```

… is copied as-is into the final server bundle. The path isn't transpiled. Do you have another suggestion on how to fix this?

**Comment by johannschopplich** [comment]
Closing this, as all issues have been resolved, except inlining the module into nitro, which seems to be necessary and has been found in other modules as well, like [nuxt-zero-js](https://github.com/danielroe/nuxt-zero-js/blob/main/src/module.ts#L22).
