### ISSUE TITLE
option to ignore self signed certificate on kql request

### ISSUE THREAD

**Issue by pixelpaulaus** [johannschopplich/nuxt-kql#17]
### Describe the feature

i have a self signed certificate on the kirby instance. And when my nuxt tries to get the data, it is stopped due to the untrusted self signed certificate. It would be great to have an option to ignore these untrusted certificates

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-kql/issues).

**Comment by johannschopplich** [comment]
I see. That's not an issue with the module or Nuxt itself, but rather your server engine. Depending on your deployment target (Node, workers, etc.), you have to allow unsigned certificates.

For example, in Node this would look as follows to run the production server:
```bash
NODE_TLS_REJECT_UNAUTHORIZED=0 node .output/server/index.mjs
```

I don't have a solution for the Cloudflare worker environment, but I'm sure there is some information online. Feel free to share your solution here for other users!
