### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by pixelpaulaus** [johannschopplich/nuxt-kql#18]
### Environment

N/A

### Reproduction

No matter what query i submit from the module. I always get a 503 error, such as:

when I output the error:

`[POST] "/api/__kirby__/%24kqll1H5ugig5r": 503 Service Unavailable`

The auth details are all correct.
Is there any reason why this would be returned from kirby?
I can login to kirbly fine.
If I sent a generic wget post request to /api/kql I get a proper response.

### Describe the bug

N/A

**Comment by johannschopplich** [comment]
Hi there!
The issue indicates that something went wrong when trying to fetch from your Kirby instance. You can read the guide to learn all about the internal [Nuxt server proxy `/api/__kirby__`](https://nuxt-kql.byjohann.dev/guide/how-it-works.html).

Please follow the issue convention and provide a reproducible example. You can use one of the templates below to create a minimal reproduction:
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

You can use my Kirby project for the reproducible example:
```ini
KIRBY_BASE_URL=https://kirby-headless-starter.jhnn.dev
KIRBY_API_TOKEN=test
```

If the issue persists and you can't reproduce it, feel free to book some consulting hours. I'd gladyl help you with your setup problems.
