### ISSUE TITLE
How to get image file content (e.g. alt text) from blocks?

### ISSUE THREAD

**Issue by igregson** [johannschopplich/nuxt-kql#2]
This is a general limitation I've hit with KQL. Wondering if you've figured out any workarounds here. 

Wasn't able to find anything from looking at the source and docs. [Your example here](https://nuxt-kql.jhnn.dev/guide/example-kirby-blocks.html) shows how to output images from blocks but not how to get their alt text (or any other field content that's stored on the file entry).

**Comment by johannschopplich** [comment]
Hey there! It's a bit tricky, as you have noticed. You'll have to fetch images for the current page with KQL to be used in blocks.

Take a look into the starter kit, specifically a notes page: https://github.com/johannschopplich/kirby-nuxt-starterkit/blob/845ecc80ce5c337a6be82acad94d2e87dab5daeb/pages/notes/%5B...id%5D.vue#L18

With the data of the current page made available globally, we can then access this data (thus, all image data) with the `useCurrentPage` composable within the [image block](https://github.com/johannschopplich/kirby-nuxt-starterkit/blob/845ecc80ce5c337a6be82acad94d2e87dab5daeb/components/Kirby/Block/Image.vue#L9).

To get image data apart from a block component, take a look into the query for `cover`.

**Comment by igregson** [comment]
Thanks @johannschopplich! 

Unfortunately the project at hand stores images at the root level of the site, so there's not a page-level image collection to query. 

Previously we simply got all images and then used a map (filename to alt text) for outputting the alt text, but this approach doesn't scale (which is why we can't use it anymore). 

I'd be nice if Kirby had some type of "auto resolve" feature. The idea is that `toFile` would always be called when returning an image (or other file) via the API. Unsure of whether to make this an official feature request or not (thoughts welcomed).

**Comment by johannschopplich** [comment]
I see. Kirby provides all the tools, you will have to write the logic, as auto-resolving is custom logic which probably won't be baked into the Kirby core.

You can add a custom file resolver yourself:

```php
use Kirby\Filesystem\F;

\Kirby\Cms\App::plugin('igregson/resolve-file', [
    'routes' => function ($kirby) {
        return [
            /**
             * Resolve a file by its path
             *
             * @returns array The file data as JSON
             */
            [
                'pattern' => 'resolve-file/(:all)',
                'action' => function ($path) use ($kirby) {
                    if (empty($path)) {
                        return [];
                    }

                    $extension = F::extension($path);

                    if (empty($extension)) {
                        return [];
                    }

                    $id = dirname($path);
                    $filename = basename($path);

                    // Try to resolve image urls for pages and drafts
                    if ($page = $kirby->site()->findPageOrDraft($id)) {
                        return $page->file($filename)->toArray();
                    }

                    // Try to resolve site files at least
                    if ($file = $kirby->site()->file($filename)) {
                        return $file->toArray();
                    }
                }
           ]
        ];
    }
]);
```

You can now fetch data for a file like `image.jpg` from the API: `/resolve-file/image.jpg`. It will return the file data as JSON.

I recommend my [kirby-headless-starter](https://github.com/johannschopplich/kirby-headless-starter) for further use and more easy setup of custom routes.

**Comment by igregson** [comment]
>Kirby provides all the tools, you will have to write the logic, as auto-resolving is custom logic which probably won't be baked into the Kirby core.

This seems to be one of the areas where Kirby suffers from not being headless-only/first (i.e. it being a traditional CMS initially and later adding headless features). It seems expected that alt text being returned with images used in blocks would work "out of the box". All the while, knowing that blocks are a new feature in Kirby, perhaps this will come at some point.

---

Your code helped point me in the right direction for my particular use case. 

I've ended up, on the Kirby side, with the below custom endpoint. It takes a `filenames` property passed in the body. It returns an object, where the each entry's key is a filename and its value is the image's alt text.

```php
'api' => [
   'routes' => function ($kirby) {
      return [
         [
            'pattern' => '/image-alts',
            'method' => 'POST',
            'action' => function () use ($kirby) {
               $body = $kirby->request()->body();

               $imageFiles = $kirby
                  ->site()
                  ->page('images')
                  ->files()
                  ->find($body->get('filenames'));

               $images = [];

               foreach ($imageFiles as $imageFile) {
                  $images[$imageFile->fileName()] = $imageFile
                     ->content()
                     ->alt()
                     ->value();
               }

               return $images;
            },
         ],
      ];
   },
],
```

Example response:

```json
{
   "quote-backgrounds5.jpeg": "Fruit tree blossoms with blurry background",
   "quote-backgrounds1.jpeg": "Grass in water",
   "quote-backgrounds2.jpeg": "White flowers on branching vegetation",
   "quote-backgrounds4.jpeg": "Flowers on plants with thick green leaves in flats",
}
```

This is how I'm extracting image strings from the Kirby layout/block objects returned via KQL:

```js
function getKirbyImageFilenames(srcObj) {
   // Returns an array of all Kirby-based image source strings by recursively traversing `srcObj`
   let imagesSources = []

   // Adapted from https://stackoverflow.com/a/722676/1971662
   function traverse(obj) {
      if (obj && typeof obj === 'object') {
         Object.entries(obj).forEach(([key, value]) => {
            // key is either an array index or object key
            traverse(value)
         })
      }
      // Otherwise, `obj` is a string or a number.
      else if (obj && typeof obj === 'string' && obj.startsWith('images/')) {
         imagesSources.push(obj)
      }
   }

   traverse(srcObj)
   return imagesSources.map((i) => i.replace('images/', ''))
}
```

---

Thanks again for sharing your insight!
