### ISSUE TITLE
Prefetching issues with using hash or query parameters

### ISSUE THREAD

**Issue by pixelpaulaus** [johannschopplich/nuxt-kql#24]
### Environment

I have noticed if I ever link to a page that is fetching any kirby content via useKql(). And I link to it via a NuxtLink that prefetches it, and the link also has a hash in it, or query. Like...
`/link/page#hash`
`/link/page?query=something`

that the SSR wont load the prefetched data, and it will attempt a new request via the kql. But because it was a static rendered nuxt site, it wont work.
Now if you visit the page directly, not via a nuxtlink, it works fine.

### Reproduction

use a NuxtLink with a hash in it

### Describe the bug

use a NuxtLink with a hash in it

**Comment by johannschopplich** [comment]
Nuxt KQL uses [`useAsyncData`](https://nuxt.com/docs/api/composables/use-async-data) under the hood. For the payload key, it [hashes the KQL query](https://github.com/johannschopplich/nuxt-kql/blob/04b4b7e4f0ef8e970fb17b72d35a4c590cb3e977/src/runtime/composables/useKql.ts#L62). If the route's hash or its query parameters are part of the KQL query, this will result in another key and thus if it wasn't prefetched before, it will initiate a new request. You have to make sure to use `useRoute().path` or a similar approach to exclude other parts of the path for your requests. 

For future issues, please always provide a reproducible example. You can use a template below to create a minimal reproduction or create a repo and link it in your issue:
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Thanks in advance!

**Comment by pixelpaulaus** [comment]
that the thing, the KQL query is not using anything from the URL, not the hash or anything. As I am using the hash to just jump to a position on the page. The KQL query is just....

`page("help/faq").children.listed`

**Comment by johannschopplich** [comment]
I see. But still, without a reproduction there is no way for me to reproduce this issue. It's not related to Nuxt KQL, but Nuxt itself. Maybe theses resources help you:
- https://github.com/nuxt/nuxt/discussions/28020
- https://github.com/nuxt/nuxt/issues/25049
- https://github.com/nuxt/nuxt/issues/9734
- https://github.com/nuxt/nuxt/issues/9448
