### ISSUE TITLE
Nuxt 3 - spa / static deployment

### ISSUE THREAD

**Issue by soerenherber** [johannschopplich/nuxt-kql#4]
Hej,

based on the "kirby-nuxt-starterkit" I am trying to create a spa. However I would like to fetch some data from client side, but as soon as I run the request at onmounted I get an "Error loading site data: 500 (/api/__kql/%24kqlmjjzAmPAEp)"

I am wondering if nuxt-kql is even intended to use at spa / static pages - I cannot find any notes regarding this in the documentation? Or maybe someone has a hint for me what kind of configuration I am missing?

Best, Sören

**Comment by johannschopplich** [comment]
Hey Sören,

intrinsically, the Kirby Nuxt Starter uses universal rendering, as almost every Nuxt application. It is server-rendered for the initial HTML response and then re-hydrates the DOM while turning into a Vue SPA. I recommend the Nuxt docs, specifically [Rendering Modes](https://nuxt.com/docs/guide/concepts/rendering) for a more thorough read. So yes, nuxt-kql suits well for client-side data fetching

To generate a completely static site, you can run `pnpm run generate` and deploy the prerendered application.

What do you intend to create? What does your setup look like? How did you connect the backend? Please provide minimal reproducible example. Thanks in advance!

**Comment by soerenherber** [comment]
Thanks for your reply! The easiest way to reproduce might be to just add the following to the kirby-nuxt-startkit:

nuxt.config.ts
```
`ssr: false'
```

pages/index.vue - jsut remove everything from the script section and add the following to make sure that it will execute:

```
onMounted(async() => {

  const { data } = await useKql({
    query: 'page("home")',
    select: {
      id: true,
      title: true,
      // description: true,
      headline: true,
      subheadline: true,
    },
  })

  setPage(() => data.value?.result)

})
```

When you run `pnpm run generate` and deploy the pages to some webserver it will tell you the following:

<img width="884" alt="Bildschirmfoto 2023-01-23 um 21 32 39" src="https://user-images.githubusercontent.com/8469867/214144197-d65ceaec-ba9a-4cec-a30a-c2b2d23d416b.png">

It tries to access some `/api/__kql/...` which simply isn't there. So I wonder if I might got some concepts wrong and if this is the case - can you give me some hint where I could start to fix this?

**Comment by johannschopplich** [comment]
I see. You try to disable Nuxt server engine, which will disable the internal Nuxt route to fetch KQL data. This approach won't work (intentionally). If you disable the server, the Nuxt server route `/api/__kql/` won't be there.

As the [docs state](https://nuxt-kql.jhnn.dev/guide/how-it-works.html):

> The [`useKql`](https://nuxt-kql.jhnn.dev/api/use-kql) and [`$kql`](https://nuxt-kql.jhnn.dev/api/kql) composables will initiate a POST request to the Nuxt server route `/api/__kql` defined by this module. The KQL query will be encoded in the request body.
>
> The internal server route then fetches the actual data for a given query from the Kirby instance and passes the response back to the template/client. Thus, no KQL requests to the Kirby instance are initiated on the client-side. This proxy behaviour has the benefit of omitting CORS issues, since data is sent from server to server.
>
> During server-side rendering, calls to the Nuxt server route will directly call the relevant function (emulating the request), saving an additional API call. Thus, only the fetch request from Nuxt to Kirby would be performed.

Thus, you won't be able to disable `ssr` without loosing the ability to fetch KQL content.

****

However, you can either:

1. Use static rendering via `pnpm run generate`
2. Or use the client-side data fetching of KQL queries

For the latter, use the `client` option for `useKql`, as [stated in the docs](https://nuxt-kql.jhnn.dev/api/use-kql.html#public-requests-in-client):

> **Public Requests in Client**
> To fetch data directly from the Kirby instance, set the option `{ client: true }`. Requires `kql.client` option to be `true` in `nuxt.config.ts` as well.

```ts
<script setup lang="ts">
const { data, pending, error, refresh } = await useKql(
  {
    query: 'site',
    select: ['title', 'children']
  },
  { client: true }
)
</script>
```

With this approach, you won't need the Nuxt server route and can disable server generation. Please see the documentation for further information.

**Comment by marco-land** [comment]
Hi @johannschopplich I am currently also running into the problem that when running `pnpm run generate`, it will pre render the pages, but all pages appear blank with client-side fetching attempts to `api/__kql/XXX` routes (which do not exist).
Is there another setting that needs to be set for static hosting? I would like to avoid client-side fetching, if possible.

I am fetching data as such:
```js
const route = useRoute();
const query = {
  query: `page('station/${route?.params?.slug}')`,
  select: {
    title: true,
  },
};
const { data } = await useKql(query, { language: locale });
```

Thanks!

**Comment by johannschopplich** [comment]
@marco-land You probably will have to enable payload extraction alongside the Nitro prerenderer. You may try:

```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      // Enable Nitro's crawler to prerender all pages (optional)
      // If Kirby content changes, the frontend will have to be rebuilt
      crawlLinks: true,
      routes: ['/'],
    },
  },

  experimental: {
    payloadExtraction: true,
  },
})
```

**Comment by marco-land** [comment]
Thanks for your quick answer! Unfortunately, it still shows a blank page and a client-side post attempt. However, if I refresh on that page, it shows the content (still with a client-side post attempt, though).

**Comment by johannschopplich** [comment]
I can't reproduce that with my [Cacao Kit](https://github.com/johannschopplich/cacao-kit-frontend). Please open a separate issue with a minimal reproduction. Thanks!

**Comment by marco-land** [comment]
OK I submitted a new [issue](https://github.com/johannschopplich/nuxt-kql/issues/10) with a small reproduction, the only difference is that in this reproduction I do not see the api fetches anymore, but pages still remain blank.
