### ISSUE TITLE
Fetching Data from localhost not working

### ISSUE THREAD

**Issue by sweidmann** [johannschopplich/nuxt-kql#8]
### Environment

Kirby Setup:

- [Kirby Headless Starter](https://github.com/johannschopplich/kirby-headless-starter) 
- Kirby ^3.9.4
- Running locally with PHP 8.0.12 Development Server (I also tried MAMP the error stays the same)
- Works on a remote Server

Nuxt Setup:

- Nuxt ^3.5.1
- Nuxt Kql ^0.26.3

### Reproduction

Hey Johann
First – thank you so much for your stellar work!

I'm running into the following problem and I can't track the error:
I try to fetch data with Nuxt3 / nuxt-kql from a locally hosted [ kirby-headless-starter](https://github.com/johannschopplich/kirby-headless-starter) backend. 
I run Kirby on `localhost:8000` using PHP 8.0.12 Development Server.

### Describe the bug

It all works fine, with the exact setup, if I deploy the backend to my shared host.
I don't get anything back if I run it locally though.

### Additional context

Do you have any ideas what the problem could be?
Many thanks! Samuel

**Comment by johannschopplich** [comment]
Can you share your (masked) environment configuration? Are you using IP v4 or v6? Make sure the local backend URL matches your Nuxt configuration.

**Comment by sweidmann** [comment]
I'm using IPv4. 

Kirby env
<img width="848" alt="backend" src="https://github.com/johannschopplich/nuxt-kql/assets/37905325/c268be04-9dab-40ac-86c0-5837a3ae54d6">

Nuxt env
<img width="758" alt="frontend" src="https://github.com/johannschopplich/nuxt-kql/assets/37905325/d7276200-0da1-4762-b133-72cfdd3e0fcd">

**Comment by johannschopplich** [comment]
Configuration seems correct. It's probably a misconfiguration on your machine. Since I don't have access, I can't help you any further, unfortunately. You could provide a minimal reproducible examples, tho.

Have you verified the KQL API endpoint is accessible? Please try a POST request via Postman or something like that to: `http://localhost:8000/api/kql`. No body needed.

**Comment by sweidmann** [comment]
Hey Johann! Many thanks for your help. Yes, I guess it must be a misconfiguration on my machine. Just thought I overlooked something. But as I said, it all works fine if I deploy the exact kirby backend to a remote shared host (with new `KIRBY_BASE_URL` in local frontend) – I also could access `http://localhost:8000/api/kql` with a POST request via Insomnia and followed the [bearer token authentication](https://nuxt-kql.byjohann.dev/guide/authentication-methods.html) guide. That all seems to be correct, since otherwise it won't work remote, I guess..

> You could provide a minimal reproducible examples, tho.
Not sure how to do that, since it all works fine remote. :-/

Will try it with one of your starter kits.

**Comment by johannschopplich** [comment]
Sounds like a plan! If you invite me to your repo, I could take a look. Maybe there _is_ something missing code-wise. But due to the limited context provided, I can't help you any further here. Sorry. 🙂
