### ISSUE TITLE
Prefetching queries in multi-language sites

### ISSUE THREAD

**Issue by marco-land** [johannschopplich/nuxt-kql#9]
### Describe the feature

The prefetching is great! Maybe I am overseeing it, but it would be great to prefetch content in different (or rather all available) languages. If this is already possible, it would be great to add something to the existing docs.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-kql/issues).

**Comment by johannschopplich** [comment]
Great feature request! What do you think about the following syntax?


```ts
// `nuxt.config.ts`
export default defineNuxtConfig({
  modules: ['nuxt-kql'],

  kql: {
    prefetch: {
      site: {
        // Define a query and its language
        query: {
          query: 'site',
          select: ['title']
        },
        language: 'de'
      }
    }
  }
})
```
